version: "2"

volumes:
  pg_data:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  db:
    container_name: mwh_database
    image: "postgres:12"
    restart: always
    tty: true
    volumes:
      - "./database/init:/docker-entrypoint-initdb.d:ro"
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "mwhdbadmin"
      POSTGRES_PASSWORD: "mwh_db_admin_password"
      POSTGRES_DB: "mwhdata"
  app:
    build:
      context: ./
    restart: always
    tty: true
    container_name: mwh_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - "db:database"
